# Generated by Django 4.0.5 on 2023-01-23 23:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('desctiption', models.TextField(blank=True, null=True)),
                ('english_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.englishword')),
            ],
        ),
        migrations.CreateModel(
            name='RussianWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('eng_translation', models.ManyToManyField(related_name='related_english', through='games.Picture', to='games.englishword')),
            ],
        ),
        migrations.AddField(
            model_name='picture',
            name='russian_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.russianword'),
        ),
        migrations.AddField(
            model_name='englishword',
            name='rus_translation',
            field=models.ManyToManyField(related_name='related_russian', through='games.Picture', to='games.russianword'),
        ),
    ]
